package com.xuesen.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xuesen.modle.Action;
import com.xuesen.modle.BabyInfo;

import com.xuesen.db.ActionDao;
import com.xuesen.db.BabyInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig actionDaoConfig;
    private final DaoConfig babyInfoDaoConfig;

    private final ActionDao actionDao;
    private final BabyInfoDao babyInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        actionDaoConfig = daoConfigMap.get(ActionDao.class).clone();
        actionDaoConfig.initIdentityScope(type);

        babyInfoDaoConfig = daoConfigMap.get(BabyInfoDao.class).clone();
        babyInfoDaoConfig.initIdentityScope(type);

        actionDao = new ActionDao(actionDaoConfig, this);
        babyInfoDao = new BabyInfoDao(babyInfoDaoConfig, this);

        registerDao(Action.class, actionDao);
        registerDao(BabyInfo.class, babyInfoDao);
    }
    
    public void clear() {
        actionDaoConfig.clearIdentityScope();
        babyInfoDaoConfig.clearIdentityScope();
    }

    public ActionDao getActionDao() {
        return actionDao;
    }

    public BabyInfoDao getBabyInfoDao() {
        return babyInfoDao;
    }

}
